### ISSUE TITLE
Gateway management

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#10]
At the moment there is no gateway management.
There is a small [API](https://github.com/Waziup/Platform/blob/master/controller/controller_spec.md) in the controller which is not completed.
How should the gateway manager component should work? Based on which technology?

**Comment by sabrine2020** [comment]
OMA LwM2M could be an option:
[http://technical.openmobilealliance.org/Technical/technical-information/release-program/current-releases/oma-lightweightm2m-v1-0](url)

**Comment by cdupont** [comment]
Postponed to V1.0.

**Comment by cdupont** [comment]
closing as too old.
