### ISSUE TITLE
lora_gateway runs almost 100 % load on RP3

### ISSUE THREAD

**Issue by Zeisberg** [Waziup/Platform#106]
The "./lora_gateway -- mode 1 ---nd1" process is causing almost 100% cpu load on the RP3 heating up the chipset.

**Comment by cdupont** [comment]
@CongducPham any update on this?

**Comment by CongducPham** [comment]
What is the exact command line you are using? Because the one you wrote here is not valid.

**Comment by cdupont** [comment]
closing as too old
