### ISSUE TITLE
Simplify FIWARE-Service and FIWARE-ServicePath

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#112]
Currently, for sensor ownership, we use the [FIWARE-Service and FIWARE-ServicePath](http://fiware-orion.readthedocs.io/en/master/user/service_path/). Those are binded to the [stakeholder](https://github.com/Waziup/Platform/blob/master/broker/broker_spec.md#orion-headers).

The FIWARE-Service and FIWARE-ServicePath are transmitted as HTTP headers when making requests to Orion.
In Orion, the FIWARE-Service resolves to a different database, while the FIWARE-ServicePath resolves to a different collection in that database.

Recent hackathons showed in my opinion that FIWARE-Service and FIWARE-ServicePath adds unnecessary complexity. They must appear is ALL curl requests, mostly unchanged during the hackathon.
So the proposal is to add default values for FIWARE-Service and FIWARE-ServicePath in Waziup platform:
```
Fiware-service = default
Fiware-ServicePath = /
```

This way, curl commands (and any REST requests) can omit the FIWARE headers.
The sensor ownership would be managed with a new field (#113) in the sensor entity instead.
This also simplifies the dashboard display of users and the identification of users by the identity proxy: in practice it is hard to retrieve the HTTP headers in both of these applications.

However, the user of the Waziup platform still has the possibility to configure the FIWARE-Service and FIWARE-ServicePath if he wants. We can add two fields in the user's settings panel on the dashboard (like it is done in [freeboard](http://www.waziup.io/documentation/tutorials/freeboard/ )

**Comment by sabrine2020** [comment]
The fiware service Path are not only for ownership, it is more about organisation.
A partner like Farmerline can have the same service Path but still can have multiple customers (farm), each customer may have their own sensors.

**Comment by ARBISWAS** [comment]
So you mean that the service path also use for the device management

**Comment by sabrine2020** [comment]
what kind of functionalities do we want in the device management?
The service Path for me is just for organisation issues
http://fiware-orion.readthedocs.io/en/master/user/service_path/

**Comment by cdupont** [comment]
@sabrine2020 Yes I think it's good to keep service path for organizational issues.
That's why I propose to keep it in the settings pane of the dashboard.
Farmerline can then configure it upon login on the dashboard.

**Comment by cdupont** [comment]
Currently, the service and servicePath are implemented this way:
- **service** is stored in the user attributes. Only an admin can change it. It is used for all Orion requests for this user. The user "waziup" currently has a service "waziup", so he will be able to see/modify only sensors in this service.
- **servicePath** is also stored in the user attributes. It is modifiable by the user via User Settings pane.
It is used following those rules:
  - Fetch sensors: use the user servicePath. If "all sensors" is checked, append a "#" character so as to get all sensors under this servicePath. For example, If your servicePath is "/", you will see only the sensors in "/". If you check "all sensors", you will see also sensors in "/FARM1/TEST".
  - Modify sensor: use the servicePath of that sensor specifically (not the user servicePath). This allow to perform a successful request for any sensor. In our example, if the sensor servicePath is "/FARM1/TEST", this servicePath will be used and the request will succeed.
  - Delete sensor: use the servicePath of that sensor specifically (not the user servicePath).
  - Fetch history of a sensor: use the servicePath of that sensor specifically (not the user servicePath).
  - Fetch notifications: use the user servicePath.

**Comment by cdupont** [comment]
Closing as it seems to be clarified.

**Comment by malishahi** [comment]
In below description it is not clear why sensors in /FARM1/TEST will be discovered while you said user's servicePath is /??

Fetch sensors: use the user servicePath. If "all sensors" is checked, append a "#" character so as to get all sensors under this servicePath. For example, If your servicePath is "/", you will see only the sensors in "/". If you check "all sensors", you will see also sensors in "/FARM1/TEST".

**Comment by cdupont** [comment]
@sabrine2020 There is a checkbox on the interface ("All Sensors") that allows you to discover all sensors in sub-servicePaths. So if your servicePath is "/", you will see sensors in "/FARM1/TEST" because it's a sub-path.
