### ISSUE TITLE
Add a sensor owner in Orion

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#113]
The proposal is to add a field "owner" in the sensor structure.
For example:

```
{
  "id": "Sensor1",
  "type": "SensingDevice",
  "owner": "cdupont",
  "temperature": {
    "value": 23,
    "type": "Number"
  },
  "pressure": {
    "value": 720,
    "type": "Number"
  }
}
```

This simplifies the creation and display of sensors in the dashboard.
The sensor can be created in Orion from the dashboard, using the login name (from keycloak) as the sensor owner name.
The sensors can also be filtered/queried more easily by owner:
```
curl http://broker.waziup.io/v2/entities?q=owner==cdupont
```

The pending question is: how to attach and enforce access policies to sensors based on ownership (using keycloak).

**Comment by sabrine2020** [comment]
How keycloak can identifiy if or not a certain user is authorized to access to a such Orion entity?
In Fiware they use:
* pep proxy to redirect the requests
* AuthZForce to manage the authorization
* KeyRock for the authentication

**Comment by cdupont** [comment]
Done. Spec is here: https://github.com/Waziup/Platform/blob/master/broker/broker_spec.md#waziup-data-model
