### ISSUE TITLE
Issue with Identity Proxy

### ISSUE THREAD

**Issue by malishahi** [Waziup/Platform#116]
[Fri Mar 03 13:28:39.759396 2017] [authz_core:debug] [pid 67] mod_authz_core.c(809): [client 10.32.0.191:51972] AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer: http://www.waziup.io/
[Fri Mar 03 13:28:39.759454 2017] [authz_core:debug] [pid 67] mod_authz_core.c(809): [client 10.32.0.191:51972] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: http://www.waziup.io/
[Fri Mar 03 13:28:39.759506 2017] [auth_openidc:debug] [pid 67] src/mod_auth_openidc.c(2981): [client 10.32.0.191:51972] oidc_check_user_id: incoming request: "/?(null)", ap_is_initial_req(r)=1, referer: http://www.waziup.io/
[Fri Mar 03 13:28:39.759544 2017] [auth_openidc:debug] [pid 67] src/util.c(853): [client 10.32.0.191:51972] oidc_util_get_cookie: returning "mod_auth_openidc_session" = <null>, referer: http://www.waziup.io/
[Fri Mar 03 13:28:39.759621 2017] [auth_openidc:debug] [pid 67] src/util.c(956): [client 10.32.0.191:51972] oidc_util_request_matches_url: comparing "/"=="/redirect_uri", referer: http://www.waziup.io/
[Fri Mar 03 13:28:39.759660 2017] [auth_openidc:debug] [pid 67] src/util.c(447): [client 10.32.0.191:51972] oidc_get_current_url: current URL 'http://dashboard.waziup.io:80/', referer: http://www.waziup.io/
[Fri Mar 03 13:28:39.759676 2017] [auth_openidc:debug] [pid 67] src/mod_auth_openidc.c(2007): [client 10.32.0.191:51972] oidc_authenticate_user: enter, referer: http://www.waziup.io/
[Fri Mar 03 13:28:39.759797 2017] [auth_openidc:debug] [pid 67] src/cache/shm.c(158): [client 10.32.0.191:51972] oidc_cache_shm_get: enter, section="provider", key="http%3A%2F%2Faam.waziup.io%2Fauth%2Frealms%2Fwaziup%2F.well-known%2Fopenid-configuration", referer: http://www.waziup.io/
[Fri Mar 03 13:28:39.760192 2017] [auth_openidc:debug] [pid 67] src/util.c(514): [client 10.32.0.191:51972] oidc_util_http_call: url=http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration, data=(null), content_type=(null), basic_auth=(null), bearer_token=(null), ssl_validate_server=1, referer: http://www.waziup.io/
[Fri Mar 03 13:28:59.780503 2017] [auth_openidc:error] [pid 67] [client 10.32.0.191:51972] oidc_util_http_call: curl_easy_perform() failed on: http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration (Resolving timed out after 5518 milliseconds), referer: http://www.waziup.io/
[Fri Mar 03 13:28:59.782318 2017] [auth_openidc:error] [pid 67] [client 10.32.0.191:51972] oidc_provider_static_config: could not retrieve metadata from url: http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration, referer: http://www.waziup.io/
[Fri Mar 03 13:28:59.889997 2017] [authz_core:debug] [pid 68] mod_authz_core.c(809): [client 10.32.0.191:52334] AH01626: authorization result of Require valid-user : denied (no authenticated user yet), referer: http://dashboard.waziup.io/
[Fri Mar 03 13:28:59.890142 2017] [authz_core:debug] [pid 68] mod_authz_core.c(809): [client 10.32.0.191:52334] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet), referer: http://dashboard.waziup.io/
[Fri Mar 03 13:28:59.890211 2017] [auth_openidc:debug] [pid 68] src/mod_auth_openidc.c(2981): [client 10.32.0.191:52334] oidc_check_user_id: incoming request: "/favicon.ico?(null)", ap_is_initial_req(r)=1, referer: http://dashboard.waziup.io/
[Fri Mar 03 13:28:59.890235 2017] [auth_openidc:debug] [pid 68] src/util.c(853): [client 10.32.0.191:52334] oidc_util_get_cookie: returning "mod_auth_openidc_session" = <null>, referer: http://dashboard.waziup.io/
[Fri Mar 03 13:28:59.890289 2017] [auth_openidc:debug] [pid 68] src/util.c(956): [client 10.32.0.191:52334] oidc_util_request_matches_url: comparing "/favicon.ico"=="/redirect_uri", referer: http://dashboard.waziup.io/
[Fri Mar 03 13:28:59.890302 2017] [auth_openidc:debug] [pid 68] src/util.c(447): [client 10.32.0.191:52334] oidc_get_current_url: current URL 'http://dashboard.waziup.io:80/favicon.ico', referer: http://dashboard.waziup.io/
[Fri Mar 03 13:28:59.890306 2017] [auth_openidc:debug] [pid 68] src/mod_auth_openidc.c(2007): [client 10.32.0.191:52334] oidc_authenticate_user: enter, referer: http://dashboard.waziup.io/
[Fri Mar 03 13:28:59.890420 2017] [auth_openidc:debug] [pid 68] src/cache/shm.c(158): [client 10.32.0.191:52334] oidc_cache_shm_get: enter, section="provider", key="http%3A%2F%2Faam.waziup.io%2Fauth%2Frealms%2Fwaziup%2F.well-known%2Fopenid-configuration", referer: http://dashboard.waziup.io/
[Fri Mar 03 13:28:59.890817 2017] [auth_openidc:debug] [pid 68] src/util.c(514): [client 10.32.0.191:52334] oidc_util_http_call: url=http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration, data=(null), content_type=(null), basic_auth=(null), bearer_token=(null), ssl_validate_server=1, referer: http://dashboard.waziup.io/
[Fri Mar 03 13:29:11.695369 2017] [mpm_prefork:notice] [pid 1] AH00173: SIGHUP received.  Attempting to restart

**Comment by malishahi** [comment]
@cdupont 
It seems Kube DNS is not working, or there are other problem that don't allow services to communicate with each other.

See below tests:

mehdi@Pole:~$ kubectl exec identityproxy-5rq5j -n waziup curl http://aam.waziup.io/auth/realms/waziup/.well-known/openid-configuration
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0curl: (6) Could not resolve host: aam.waziup.io; Unknown error
mehdi@Pole:~$ kubectl exec identityproxy-5rq5j -n waziup curl http://aam.waziup/auth/realms/waziup/.well-known/openid-configuration
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0curl: (6) Could not resolve host: aam.waziup; Unknown error
mehdi@Pole:~$ kubectl exec identityproxy-5rq5j -n waziup curl http://aam/auth/realms/waziup/.well-known/openid-configuration
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:19 --:--:--     0curl: (6) Could not resolve host: aam; Unknown error

**Comment by cdupont** [comment]
Exactly, the DNS was not working. I restarted kube-dns pod, now everything is working again.
