### ISSUE TITLE
Historical data API

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#12]
Currently there is no interface to retrieve historical data from Waziup.
How does this interface should look like? How to retrieve the data from MongoDB?

**Comment by sabrine2020** [comment]
I came across these tools for MongoDB to use a http interface:
[https://docs.mongodb.com/ecosystem/tools/http-interfaces/](url)

**Comment by cdupont** [comment]
assigned to @DiopBabacarEdu

**Comment by cdupont** [comment]
@DiopBabacarEdu any update?

**Comment by diopBabacar** [comment]
**Eve-Demo** is a fully featured RESTful Web API powered by Eve (http://python-eve.org) that supports MongoDB backend. 
For setting an API with Eve, two scripts are required :
- run.py (a launch script )
- settings.py (a configuration file)

The codebase is thoroughly tested under Python 2.6, 2.7, 3.3, 3.4 and PyPy.

`import os

# We want to seamlessy run our API both locally and on Heroku. If running on
# Heroku, sensible DB connection settings are stored in environment variables.
MONGO_HOST = os.environ.get('MONGO_HOST', 'localhost')
MONGO_PORT = os.environ.get('MONGO_PORT', 27017)
MONGO_USERNAME = os.environ.get('MONGO_USERNAME', 'user')
MONGO_PASSWORD = os.environ.get('MONGO_PASSWORD', 'user')
MONGO_DBNAME = os.environ.get('MONGO_DBNAME', 'evedemo')


# Enable reads (GET), inserts (POST) and DELETE for resources/collections
# (if you omit this line, the API will default to ['GET'] and provide
# read-only access to the endpoint).
RESOURCE_METHODS = ['GET', 'POST', 'DELETE']

# Enable reads (GET), edits (PATCH) and deletes of individual items
# (defaults to read-only item access).
ITEM_METHODS = ['GET', 'PATCH', 'DELETE']

# We enable standard client cache directives for all resources exposed by the
# API. We can always override these global settings later.
CACHE_CONTROL = 'max-age=20'
CACHE_EXPIRES = 20

# Our API will expose two resources (MongoDB collections): 'people' and
# 'works'. In order to allow for proper data validation, we define beaviour
# and structure.
people = {
    # 'title' tag used in item links.
    'item_title': 'person',

    # by default the standard item entry point is defined as
    # '/people/<ObjectId>/'. We leave it untouched, and we also enable an
    # additional read-only entry point. This way consumers can also perform GET
    # requests at '/people/<lastname>/'.
    'additional_lookup': {
        'url': 'regex("[\w]+")',
        'field': 'lastname'
    },

    # Schema definition, based on Cerberus grammar. Check the Cerberus project
    # (https://github.com/nicolaiarocci/cerberus) for details.
    'schema': {
        'firstname': {
            'type': 'string',
            'minlength': 1,
            'maxlength': 10,
        },
        'lastname': {
            'type': 'string',
            'minlength': 1,
            'maxlength': 15,
            'required': True,
            # talk about hard constraints! For the purpose of the demo
            # 'lastname' is an API entry-point, so we need it to be unique.
            'unique': True,
        },
        # 'role' is a list, and can only contain values from 'allowed'.
        'role': {
            'type': 'list',
            'allowed': ["author", "contributor", "copy"],
        },
        # An embedded 'strongly-typed' dictionary.
        'location': {
            'type': 'dict',
            'schema': {
                'address': {'type': 'string'},
                'city': {'type': 'string'}
            },
        },
        'born': {
            'type': 'datetime',
        },
    }
}

works = {
    # if 'item_title' is not provided Eve will just strip the final
    # 's' from resource name, and use it as the item_title.
    #'item_title': 'work',

    # We choose to override global cache-control directives for this resource.
    'cache_control': 'max-age=10,must-revalidate',
    'cache_expires': 10,

    'schema': {
        'title': {
            'type': 'string',
            'required': True,
        },
        'description': {
            'type': 'string',
        },
        'owner': {
            'type': 'objectid',
            'required': True,
            # referential integrity constraint: value must exist in the
            # 'people' collection. Since we aren't declaring a 'field' key,
            # will default to `people._id` (or, more precisely, to whatever
            # ID_FIELD value is).
            'data_relation': {
                'resource': 'people',
                # make the owner embeddable with ?embedded={"owner":1}
                'embeddable': True
            },
        },
    }
}

# The DOMAIN dict explains which resources will be available and how they will
# be accessible to the API consumer.
DOMAIN = {
    'people': people,
    'works': works,
}`


`
"""
    Eve Demo
    ~~~~~~~~
    A demostration of a simple API powered by Eve REST API.
    The live demo is available at eve-demo.herokuapp.com. 
"""

import os
from eve import Eve

# Heroku support: bind to PORT if defined, otherwise default to 5000.
if 'PORT' in os.environ:
    port = int(os.environ.get('PORT'))
    # use '0.0.0.0' to ensure your REST API is reachable from all your
    # network (and not only your computer).
    host = '0.0.0.0'
else:
    port = 5000
    host = '127.0.0.1'

app = Eve()


if __name__ == '__main__':
    app.run(host=host, port=port)`

**Comment by cdupont** [comment]
@Babacar personnaly I use Swagger to generate the API interface.
At the moment we just need to define an API to retrieve historical data and implement it.
Could you propose some end points? For example `/data/history`...
Probably it should use the same format than the existing end points (i.e. Orion/IoT-Lite...)

**Comment by DiopBabacarEdu** [comment]
Using Swagger for historical Api design seems to be easier and brings down more flexibility. The following description is proposed. 

`
---
swagger: "2.0"
info:
  version: "1.0"
  title: "WAZIUP API Testing"
host: "www.waziup.io:30333"
basePath: "/api/v1"
tags:
- name: "apps"
  description: "Applications API"
- name: "data"
  description: "data management API"
- name: "gateways"
  description: "gateway management API"
paths:
  /data/db/history:
    get:
      tags:
      - "data"
      operationId: "controllers.default_controller.data_history_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "get historical data"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Observation"
      x-tags:
      - tag: "data"
  
  /data/db/history/{id}:
    get:
      tags:
      - "data"
      operationId: "controllers.default_controller.data_history_id_get"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
#        minimum: 0.0
      responses:
        200:
          description: "Get history data of a given entity"
          schema:
            $ref: "#/definitions/Observation"
        404:
          description: "`id` not found"
      x-tags:
      - tag: "data"
      
definitions:
  
  Observation:
    type: "object"
    properties:
      id:
        type: "string"
        example: "TemperatureSensor1"
      type:
        type: "string"
        example: "SensingDevice"
      measure:
        $ref: "#/definitions/Measure"
      location:
        $ref: "#/definitions/Location"
      platform:
        type: "string"
        example: "UGB Field"
  Measure:
    type: "object"
    properties:
      value:
        type: "number"
        format: "float"
        example: 27
      metadata:
        $ref: "#/definitions/MeasureMetadata"
  MeasureMetadata:
    type: "object"
    properties:
      dimension:
        type: "string"
        example: "temperature"
      unit:
        type: "string"
        example: "Celcius"
      timestamp:
        type: "string"
        format: "dateTime"
        example: "2016-06-08T18:20:27.873Z"
  Location:
    type: "object"
    properties:
      type:
        type: "string"
        example: "Point"
        enum:
        - "MultiPolygon"
        - "Point"
      coordinates:
        type: "array"
        items:
          type: "array"
          items:
            type: "number"
    externalDocs:
      url: "http://geojson.org/geojson-spec.html#geometry-objects"
    description: "Geometry as in GeoJSON."`

**Comment by diopBabacar** [comment]
**.yaml file**

```

---
swagger: "2.0"
info:
  version: "1.0"
  title: "WAZIUP API Testing"
host: "www.waziup.io:30333"
basePath: "/api/v1"
tags:
- name: "apps"
  description: "Applications API"
- name: "data"
  description: "data management API"
- name: "gateways"
  description: "gateway management API"
paths:
  /data/db/history:
    get:
      tags:
      - "data"
      operationId: "controllers.default_controller.data_history_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "get historical data"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Observation"
      x-tags:
      - tag: "data"
  
  /data/db/history/{id}:
    get:
      tags:
      - "data"
      operationId: "controllers.default_controller.data_history_id_get"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "Get history data of a given entity"
          schema:
            $ref: "#/definitions/Observation"
        404:
          description: "`id` not found"
      x-tags:
      - tag: "data"
      
definitions:
  
  Observation:
    type: "object"
    properties:
      id:
        type: "string"
        example: "TemperatureSensor1"
      type:
        type: "string"
        example: "SensingDevice"
      measure:
        $ref: "#/definitions/Measure"
      location:
        $ref: "#/definitions/Location"
      platform:
        type: "string"
        example: "UGB Field"
  Measure:
    type: "object"
    properties:
      value:
        type: "number"
        format: "float"
        example: 27
      metadata:
        $ref: "#/definitions/MeasureMetadata"
  MeasureMetadata:
    type: "object"
    properties:
      dimension:
        type: "string"
        example: "temperature"
      unit:
        type: "string"
        example: "Celcius"
      timestamp:
        type: "string"
        format: "dateTime"
        example: "2016-06-08T18:20:27.873Z"
  Location:
    type: "object"
    properties:
      type:
        type: "string"
        example: "Point"
        enum:
        - "MultiPolygon"
        - "Point"
      coordinates:
        type: "array"
        items:
          type: "array"
          items:
            type: "number"
    externalDocs:
      url: "http://geojson.org/geojson-spec.html#geometry-objects"
    description: "Geometry as in GeoJSON."
```

**Below is code for back-end management**
Actions 👍 

- Connect to a mongodb instance running at mongodb://localhost:27017/local

- Query history data 

```
var express = require('express');
var app = express();

var mongodb = require('mongodb');
var MongoClient = mongodb.MongoClient;
var url = 'mongodb://localhost:27017/local';
var not_csl;

app.get('', function (req, res) {
   console.log("Got a GET request for ... ");
   MongoClient.connect(url, function (err, db) {
   if (err) {
     console.log('Unable to connect to MongoDB server. Error:', err);
   } else {
     console.log('Connection established to', url);
     var collection = db.collection('users');

     collection.find().toArray(function (err, result) {
       if (err) {
         console.log(err);
       } else if (result.length) {
         console.log('Found:', result);
         not_csl = result;
       } else {
         console.log('No document found !');
       }
       db.close();
     });
   }
   });
   res.send(not_csl);
})

var server = app.listen(8081, function () {

   var host = server.address().address
   var port = server.address().port

   console.log("Server listening at http://%s:%s", host, port)
})
```

**Comment by diopBabacar** [comment]
## Containerization

**Dockerfile**

```
FROM google/nodejs
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
RUN npm install

COPY . /usr/src/app

EXPOSE 8081
CMD [ "npm", "start" ]
```

**package.json**

```
{
  "name": "waziup_mongo_nodejs",
  "version": "1.0.0",
  "description": "Read Data From DB",
  "author": "Waziup Agent <www.waziup.org>",
  "main": "server.js",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.14.0",
    "mongodb": "^2.2.11",
    "body-parser": "^1.15.2",
    "cookie-parser": "^1.4.3"
  }
}
```

**server.js**

```
var express = require('express');
var app = express();

var mongodb = require('mongodb');
var MongoClient = mongodb.MongoClient;
var not_csl;

app.get('/', function (req, res) {
   console.log("Got a GET request for ... ");

   var url = 'mongodb://localhost:27017/' + req.query.dbName;
   MongoClient.connect(url, function (err, db) {
   if (err) {
     console.log('Unable to connect to MongoDB server. Error:', err);
   } else {
     console.log('Connection established to', url);
     var collectionName = req.query.colName;
     var collection = db.collection(collectionName);

     collection.find({id: req.query.id}).toArray(function (err, result) {
       if (err) {
         console.log(err);
       } else if (result.length) {
         console.log('Found:', result);
         not_csl = result;
       } else {
         console.log('No document found !');
       }
       db.close();
     });
   }
   });
   res.send(not_csl);
})

  var server = app.listen(8080, function () {
  var host = server.address().address
  var port = server.address().port
  console.log("Server listening at http://%s:%s", host, port)
})
```

**Comment by cdupont** [comment]
@DiopBabacarEdu I pushed your files here: https://github.com/Waziup/Platform/tree/master/broker/history
Could you give instructions on how to use it in the README file?

**Comment by cdupont** [comment]
The current API is difficult to use, because one need to know the entity id, database name and collection name... Anyway I would close this issue as soon as it is working for V0.2.

**Comment by cdupont** [comment]
I was able to test it. See test file: https://github.com/Waziup/Platform/blob/master/broker/history/history_test.md
Closing.

**Comment by cdupont** [comment]
It is now online and testable using the same file.
