### ISSUE TITLE
A page for tokens in dashboard

### ISSUE THREAD

**Issue by malishahi** [Waziup/Platform#122]
We need a page to show all tokens in dashboard. This can be required by CLI-based operations.

**Comment by cdupont** [comment]
Good idea. Are you thinking about identity tokens? Or other tokens?
This page can be located in settings or profile...

**Comment by malishahi** [comment]
Tokes are identity token, access token, and refresh token. I guess in keycloak output access token corresponds to token.

**Comment by cdupont** [comment]
Obsolete with the new dashboard/API.
