### ISSUE TITLE
Cors Error on Orion Broker

### ISSUE THREAD

**Issue by ousmaneo** [Waziup/Platform#123]
Request to Orion for sensors and others result on a: 

`OPTIONS http://orion.waziup.io/v1/data/entities 404 (Not Found)`

The error message is: 
`XMLHttpRequest cannot load http://orion.waziup.io/v1/data/entities. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access. The response had HTTP status code 404.`

This is mostly related CORS issue.

**Comment by malishahi** [comment]
Give it a try, it should be working now.

**Comment by ousmaneo** [comment]
Working. Fixed

Closing this issue
