### ISSUE TITLE
default plot graphic for sensors

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#125]
On the sensor specific page, a graphic should be displayed showing the history of the values of that sensor.
If the sensor has standard measurements such as "Temperature" or "Pressure", it should be recognized and plotted.

D3 library could be used.

**Comment by malishahi** [comment]
This is a sample of line chart https://bl.ocks.org/mbostock/3883245.
We can take this to draw a line chart for temperature sensors, for example.

I need to know to how I access the data?, and in the timescale what is the percision?

 I mean in minutes, hours, seconds. I guess we can go into minutes, or hours.

**Comment by cdupont** [comment]
Done.
