### ISSUE TITLE
Social network notifications

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#126]
Create a panel to set up the notifications. The panel should be common to all social networks.

**Comment by pandaconstantin** [comment]
UI for the notification settings done. Here the link on github
https://github.com/pandaconstantin/notificationapipub/tree/master/waziup-dashboard

To be done : 
Attach URI to UI in order to send or pull data from database

**Comment by pandaconstantin** [comment]
[](url)

**Comment by pandaconstantin** [comment]
[](url)

**Comment by cdupont** [comment]
Great!
Could you make a pull request on the repo?
https://github.com/Waziup/waziup-dashboard

**Comment by cdupont** [comment]
Closing as too old.
