### ISSUE TITLE
Social networks settings panel

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#127]
Create a settings panel for:
- Facebook
- Twitter
- Whatsapp

The panel should contain: TBD.

The data should be save in Keycloak.

**Comment by pandaconstantin** [comment]
- Social media settings page :  



- Notification settings page :

**Comment by ARBISWAS** [comment]
As discussed in the call, for being less keep it simple all the setting can come in one page (notification page)

**Comment by cdupont** [comment]
Done
