### ISSUE TITLE
Security and identification

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#13]
Currently there is no identification/security in the platform.
Anybody can push data or an application.
How to implement identification and security?

**Comment by cdupont** [comment]
Concerning the Orion proxy, Wilma could be a solution. 
It is a Fiware GE working with two other GEs (Keywork and AuthZForce) that implements security layer for back-end services.

One could use it for controlling access to public back-end services (endpoints in Waziup).
It has three levels of security, and the third level is based on XACML policies. 
We now should check if it is possible to enforce users' entities/attributes to respect IoT-Lite format using XACML policies.
https://edu.fiware.org/course/view.php?id=131
https://edu.fiware.org/course/view.php?id=79

**Comment by sabrine2020** [comment]
check this link for the proxy solutions:
[http://stackoverflow.com/questions/37110833/fiware-orion-and-pep-proxy-solutions](url)

I think we should consider looking at the over all security solution before start looking at the proxy for Orion. Other solutions like:
*OpenAM
*Gluu

**Comment by cdupont** [comment]
@sabrine2020 do you agree to take this issue? Milestone is V0.3 so not immediately.

**Comment by sabrine2020** [comment]
sorry I can't, I am working on the MVP water.

**Comment by cdupont** [comment]
let's check also keystone: http://docs.openstack.org/developer/keystone/
it can be linked with kubernetes: http://kubernetes.io/docs/admin/authentication/

**Comment by cdupont** [comment]
Keystone was selected and installed, closing.
