### ISSUE TITLE
Attribute Value types available ?

### ISSUE THREAD

**Issue by tteixeira** [Waziup/Platform#138]
When creating a sensor and trying to use type: "String" and add a value "UT1234" returns a bad request 

"error":"BadRequest","description":"attribute value type not recognized"

I want to push a Unix timestamp, however using the type "Number", approximates the number (e.g. pushing 1491305984 and accessing the value, returns 1.49131e+09 = 1491310000). 

Is there any different types we can use to solve this issue ?

**Comment by cdupont** [comment]
Did you try with the type DateTime?

**Comment by sabrine2020** [comment]
Could you share your Post request?
for more details abour NGSI requests: [http://docs.orioncontextbroker.apiary.io/#reference/attributes](url)

**Comment by tteixeira** [comment]
DateTime solved it! Thanks for the help!
