### ISSUE TITLE
Mobile app back-end: link with WAZIUP

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#14]
Currently the mobile app is not linked with WAZIUP.
How should it connect?

**Comment by cdupont** [comment]
Currently the Orion broker is exposed at: `www.waziup.io:30026`
Test that is works with:
```
$ curl www.waziup.io:30026/version
```

You can create a sensor measuring temperature and pressure (with initial values) like that:
```
$ curl http://www.waziup.io:30026/v2/entities -s -S --header 'Content-Type: application/json' -X POST -d @- <<EOF
{
  "id": "Sensor1",
  "type": "SensingDevice",
  "temperature": {
    "value": 23,
    "type": "Number"
  },
  "pressure": {
    "value": 720,
    "type": "Number"
  }
}
EOF
```

Further updates of the values are like that:
```
$ curl http://www.waziup.io:30026/v2/entities/Sensor1/attrs/temperature/value -s -S --header 'Content-Type: text/plain' -X PUT -d 27
```
To retrieve the last data point inserted:
```
$ curl http://www.waziup.io:30026/v2/entities/Sensor1/attrs/temperature/value -X GET
```

**Comment by ousmaneo** [comment]
Hi @cdupont ,
we are integrating to the mobile app, but we have some issue with orion.
- Trying to get the list of Sensors 
-- GET http://broker.waziup.io/v2/entities
But the result is an empty array.
can you give me more direction on the way to get it.
NB: i created sensors before trying to get them back.

**Comment by cdupont** [comment]
Hi @ousmaneo, how did you created the sensors?
There is a working example here: https://github.com/Waziup/Platform/blob/master/broker/README.md

**Comment by ousmaneo** [comment]
Hi,
I used the example here to create the sensors, and i says sensors created 
but when i try to get sensors list it returns an empty object ([]).

Regards

**Comment by cdupont** [comment]
I updated the linked example with the command to retrieve sensors. Contact me on Skype if it's not working.

**Comment by ousmaneo** [comment]
Thanks it's working.

**Comment by cdupont** [comment]
closed with https://github.com/Waziup/Platform/commit/89fc8f7cdddc3a7baae709cbe8389e346675d86c

**Comment by fizarbd** [comment]
@ousmaneo, I think, you have not added the option to change the service path like as from TEST to IT21 in this released apk . Is there any way to check IT21 sensor data using this app?
