### ISSUE TITLE
Add new sensor - Measurement selection

### ISSUE THREAD

**Issue by ARBISWAS** [Waziup/Platform#140]
Should we add a pop-down menu of the sensor measurement filed

**Comment by ARBISWAS** [comment]
Similarly for the Unit a pop-down list

**Comment by cdupont** [comment]
Yes we are working on it. There are two things to do:
- a drop-down list pre-filed with Fiesta ontology for measurement, for selecting the measurement type (temperature, pressure etc.)
- a "Add a new measurement" button to add a new measurement line (a sensor can have several measurements)

**Comment by cdupont** [comment]
Done
