### ISSUE TITLE
platform installation with docker

### ISSUE THREAD

**Issue by j-forster** [Waziup/Platform#141]
following the install instructions from INSTALL.md
```
  git clone git@github.com:Waziup/Platform.git
  cd platform
  docker-compose up
```
I end up with the docker error:
```
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```
As there are no docker-compose.yml, docker-compose.yaml files inside the root directory,
what else can i do to install the platform?

**Comment by cdupont** [comment]
Hi Johann,
the platform doesn't have an automated install procedure yet. 
We are working on it: https://github.com/Waziup/Platform/issues/72

**Comment by cdupont** [comment]
done: docker-compose up should work.
