### ISSUE TITLE
broker cross-Origin, OPTIONS method not allowed

### ISSUE THREAD

**Issue by j-forster** [Waziup/Platform#142]
The broker works very well with `curl` or in the browser  ([http://broker.waziup.io](http://broker.waziup.io/v2/entities)), but fetching data from other domains (that are limited to cross-origin security) fails.

For example: My WebApp, which is using the waziup broker, requests ([http://broker.waziup.io](http://broker.waziup.io/v2/entities)) using [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API), must schedule an `OPTIONS` request first, before the main GET request.
However, the `OPTIONS` request fails:
_Request Headers:_
```
OPTIONS /v2/entities HTTP/1.1
Access-Control-Request-Headers: fiware-service,fiware-servicepath
Access-Control-Request-Method: GET
Origin: http://my-domain.com
```
_Response Headers:_
```
HTTP/1.1 405 Method Not Allowed
Allow: POST, GET
```

The [dashboard](http://dashboard.waziup.io) avoids this conflict using [orion.waziup.io](http://orion.waziup.io/v1/data/entities).

So should i use `orion.waziup.io` in general, or are you going to implement the cross-origin functionality for `broker.waziup.io`? (Or is using the broker with other WebApp not intended?)
Thanks in advance!

**Comment by cdupont** [comment]
Hi Johann,
good call.
You're right, Orion doesn't support CORS: https://github.com/telefonicaid/fiware-orion/issues/501
So in Waziup we added a proxy that adds the CORS responses: https://github.com/Waziup/Platform/blob/master/identity/identityproxy.conf#L11
This is documented here: http://www.waziup.io/documentation/api/api-reference/

So yes, you can use http://orion.waziup.io/v1/data/entities from a WebApp.

**Comment by cdupont** [comment]
@j-forster is it resolved?

**Comment by j-forster** [comment]
Yes, thanks for your answer.
