### ISSUE TITLE
delete sensors, HTTP DELETE request

### ISSUE THREAD

**Issue by j-forster** [Waziup/Platform#143]
Hi @cdupont 
thanks so far for your help!

As i can see, the `HTTP Delete`-Request is not listed at
https://github.com/Waziup/Platform/blob/master/identity/openidc-keycloak/identityproxy.conf#L30
I think, this isn't intentionally?
In particular: I created a test-sensor and can not delete the dummy values/attrs I just inserted..

Thanks in advance!

**Comment by cdupont** [comment]
It's corrected: https://github.com/Waziup/Platform/blob/master/identity/proxy/identityproxy.conf#L12

**Comment by cdupont** [comment]
@j-forster, I would be interested to know on which application are you working on? It looks interesting. As Waziup is an Open-Source project, we could contribute! We can discuss on my private email: corentin.dupont@gmail.com
