### ISSUE TITLE
Old data is displayed on dashboard

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#146]
The sensors displayed on the dashboard are old and have been deleted.
It seems that mongoDB restarted and picked up an old DB file.

**Comment by j-forster** [comment]
The broker is down - and http://orion.lab.fiware.org/v2/entities is unreachable, too?

**Comment by cdupont** [comment]
Now the broker should be back up: `curl http://broker.waziup.io/version`
I don't know about fiware.org?

**Comment by j-forster** [comment]
But http://broker.waziup.io/v2/entities is empty, and http://orion.lab.fiware.org/v2/entities times out?

**Comment by cdupont** [comment]
This happened again today.
We tried to fix it by removing the --nojournal argument that was on the mongod: https://github.com/Waziup/Platform/commit/11403bc0556298761ee9bfd569dacf5fc6ec7bc1
