### ISSUE TITLE
Waziup new API

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#148]
Currently the API is like that:

**Context Broker:**
orion.waziup.io/v1/data -> internal endpoint: orion.waziup:1026/v2

**Historical Database:**
historicaldata.waziup.io -> internal endpoint: sth-comet.waziup:8666/

**SMS Services:**
sms.waziup.io/v1/sms/send  -> external endpoint: messaging.mergdata.com/api/v1/sms/send
sms.waziup.io/v1/sms/receive -> internal endpoint: smsserver.waziup:80/v1/sms/receive 
sms.waziup.io/v1/sms/register -> internal endpoint: smsserver.waziup:80/v1/sms/register

There are some problems with this API:
1. Orion V1 API is not reachable (orion.waziup:1026/v1)
2. The use of subdomains (XXX.waziup.io) for routing the API makes it difficult to run on localhost or another server/domain.
3. the API is not well "concentrated": all the endpoints should be under the label or folder "api".
4. the API is not well versionned.

**Comment by j-forster** [comment]
To begin the conversation:
A single endpoint for API access can be done by
http://api.waziup.io
This should be split by versions like
http://api.waziup.io/v1 and http://api.waziup.io/v2 (Waziup API versions)
Resulting in single API endpoints
http://api.waziup.io/v2/orion -> (internal) orion.waziup:1026
http://api.waziup.io/v2/sms/recieve -> (internal) smsserver.waziup:80/v1/sms/receive
...
One can reach Orion V1 and V2 (from Waziup API version 3) with 
http://api.waziup.io/v3/orion/v1 and http://api.waziup.io/v3/orion/v2

**Comment by cdupont** [comment]
I agree with this.

**Comment by cdupont** [comment]
Closing as obsolete (see D3.1 report for the complete API).
