### ISSUE TITLE
sensors dashboard

### ISSUE THREAD

**Issue by sabrine2020** [Waziup/Platform#153]
It is good to have the time/date of the last received value:

![image](https://cloud.githubusercontent.com/assets/11886594/26146417/633ab458-3af0-11e7-9cbd-530a3dafe42b.png)

**Comment by cdupont** [comment]
I was thinking of adding a light showing the status of the sensor: 
green = value received in the last day
yellow = value received in the last week
red = more than one week

Regarding the date/time, which one to display? The "last update" time at sensor level? or at measurement level?
It could be display like that:

- AZO: 3.31 (at 13:00)
- DO: 0 (at 13:05)
- HU: 60 (at 13:05)
- LU: 0.34 (at 13:05)
- RC: 0 (at 13:00)
- TC: 23.67 (at 13:00)
- WC: 0 (3 days ago)
- WD: -1 (never)

Or: 

- AZO: 3.31
- DO: 0
- HU: 60
- LU: 0.34
- RC: 0
- TC: 23.67
- WC: 0
- WD: -1
Updated one hour ago

The "vague times" can be computed using this package: https://www.npmjs.com/package/vague-time
Also, I thing columns "type" and "owner" are not useful for this table, which is just an overview.

**Comment by cdupont** [comment]
Also note that the units are missing.

**Comment by sabrine2020** [comment]
well... on one hand since the time in the measurment level can be different than the one in the sensor level, it is better to have it in the measurment level. On the other hand having the time in each measurement it is not very readble...It is clearer to have the list of measurment then the time..
Also the use of DO, HU is not very human readble...

**Comment by cdupont** [comment]
It is done in the new dashboard. To get the timestamp just hover the sensor with the mouse.
