### ISSUE TITLE
browser compatilibity of keycloak-admin-client

### ISSUE THREAD

**Issue by teegwende** [Waziup/Platform#158]
Hi
I can't run locally neither waziup-dashboard master branch neither notif branch on iceweasel-firefox ESR 45.9.
when i run it the browser launches but it just shows localhost:3000 and nothing else.
I opened the web console to check and I see "SyntaxError: invalid for/in left-hand side" .

See attached some pictures

![details_of_error](https://cloud.githubusercontent.com/assets/26285604/26784589/04e5da92-49ee-11e7-9512-17e3d8f1289a.png)
![page_obtained](https://cloud.githubusercontent.com/assets/26285604/26784590/04e889c2-49ee-11e7-9ba9-b76358a86212.png)

Notice that i can run it on google chrome (version 58.0.3)

**Comment by cdupont** [comment]
The wrong line seems to be here: https://github.com/bucharest-gold/keycloak-admin-client/blob/18cc66f7b51e4964844c369b313cf3cd4602c618/lib/kc-admin-client.js#L16

**Comment by cdupont** [comment]
@teegwende could you update this issue? It seems that the problem was solved upstream.
