### ISSUE TITLE
deploy the SMS server on WAZIUP

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#17]
- Create the dockerfile
- Create the Kubernetes file
- deploy on Waziup platform

**Comment by joelbudu** [comment]
I encountered an error when I tried to run 
`FROM tutum/apache-php`
this was the response
`FROM: can't read /var/mail/tutum/apache-php`


was following this as a guide [https://github.com/tutumcloud/apache-php](url)

**Comment by cdupont** [comment]
@joelbudu it's not clear at which step you had this error.

**Comment by cdupont** [comment]
I'm trying to deploy the SMS server with this file: https://github.com/Waziup/Platform/blob/master/UIManager/SMS/SMSServer.yaml

It fails with the error:
```
 2016-11-21T10:22:51.336407983Z 2016/11/21 10:22:51 [emerg] 1#1: host not found in upstream "php" in /etc/nginx/conf.d/default.conf:16
2016-11-21T10:22:51.336467949Z nginx: [emerg] host not found in upstream "php" in /etc/nginx/conf.d/default.conf:16 
```

**Comment by cdupont** [comment]
We should embed the SMS Server directly in Waziup.
In the mean time, I created a forward to mergdata:
https://github.com/Waziup/Platform/blob/master/controller/nginx.conf

You can use it like that:
```
$ curl -X POST -H "Content-Type: application/json" -H "Api-Token: 53fdb4b2-0ad4-4767-99ea-2271f16f6f1d" -H "Cache-Control: no-cache" -H "Postman-Token: d424994b-27dd-1f5a-4151-a8b2aa0ac22b" -d '{
"sender_id" : "WAZIUP",
"contacts" : ["+393806412093"],
  "message" : "Testing"
}' "http://api.waziup.io/v1/sms/send"
{"status":"success","status_code":"1000","status_text":"Message is successfully initiated","sms_succeeded":"[0]","sms_failed":"[]"}
```

**Comment by cdupont** [comment]
It's working, closing. Thanks Joel!
