### ISSUE TITLE
Use gateway timestamp in dashboard

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#171]
Currently, the dashboard displays the time at which values are received on the Cloud platform.
It's called "dateModified" in the code.
However this is not the correct time, since the gateway might send the data points in a delayed manner.
The solution is to use the measurement timestamp instead:
```
curl --include --request POST --header "Content-Type: application/json" "{ \
 \"TC\": { \
   \"value\": 27, \
   \"metadata\": { \
       \"timestamp\": { \
                   \"type\": \"DateTime\", \
                   \"value\": \"2017-01-27T10:00:13.000\" \
               } \
   } \
 } \
} \
'http://broker.waziup.io/v2/entities/UPPASensor2/attrs/'
```

**Comment by cdupont** [comment]
In feeder.js :
``` 
302                 bulkBody.push({
303                     name: sensor.name,
304                     attribute: attribute.name,
305                     time: sensor.dateModified,
306                     value: attrVal
```
dateModified is used, but probably we need to put attribute.metadata.timestamp.value

What to do if timestamp is not available?

**Comment by malishahi** [comment]
Done
