### ISSUE TITLE
access denied while pulling the els-feeder sub module from the repo

### ISSUE THREAD

**Issue by henokzion** [Waziup/Platform#172]
here is the error log when trying to pull with docker-compose 
ERROR: pull access denied for waziup/els-feeder, repository does not exist or may require 'docker login'

**Comment by cdupont** [comment]
Mehdi is currently fixing the els-feeder.
When this is finished, he will push an image to dockerhub, this should fix this issue.

**Comment by cdupont** [comment]
done
