### ISSUE TITLE
HTTPS do not work

### ISSUE THREAD

**Issue by Rotzbua** [Waziup/Platform#176]
Main page:
https://www.waziup.io/
Also auth page:
https://aam.waziup.io

Or you guys and girls really transfer passwords unencrypted in 2018?

**Comment by cdupont** [comment]
Good point!
HTTPS is actually included for the V2 of the platform (coming soon).
https://github.com/Waziup/api-server/blob/master/src/index.js#L69

**Comment by cdupont** [comment]
done

**Comment by cdupont** [comment]
@Rotzbua could you give the command you are using?
