### ISSUE TITLE
Error while trying to retrieve non-existent domain with admin previledges

### ISSUE THREAD

**Issue by henokzion** [Waziup/Platform#177]
the server returns with 500 instead of the expected 404 error message.

**Comment by cdupont** [comment]
It's a Keycloak bug. I reported here: https://issues.jboss.org/browse/KEYCLOAK-5901
It should be resolved already in the new version of Keycloak 3.4.1.
I will updated the version of Keycloak to solve this problem.

**Comment by cdupont** [comment]
Done. The result should be 403: Forbidden because deleting a non existing resource is forbidden by Keycloak.
Could you retry?

**Comment by henokzion** [comment]
It's fixed now

**Comment by cdupont** [comment]
Thanks Henok, if it's fixed please close the issue.
