### ISSUE TITLE
SMS server API

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#18]
Currently an API has been provided for the SMS server: https://github.com/Waziup/Platform/blob/master/UIManager/SMS/swagger.json
Should it be merged with the other APIs and exposed in the controller?

**Comment by joelbudu** [comment]
Yes @cdupont Lets merge it with the other APIs exposed

**Comment by cdupont** [comment]
@joelbudu how should we do to expose it with the other APIs?
Should we expose it with nginx?
The APIs are exposed by the controller. Now the controller is a Python program doing the translation between external API and internal API. But I am more an more thinking of replacing it by a simpler solution like nginx.
