### ISSUE TITLE
last_value is missing in getSensors API

### ISSUE THREAD

**Issue by malishahi** [Waziup/Platform#184]
for SM1 attribute, last_value is missing.
why getSensors does not include last_value?

[{"id":"IT21_Sensor2","gateway_id":"5a494b5f5d1531c941caba877965ac22","name":"","owner":"","measurements":[{"id":"SM1","timestamp":"2018-03-29T11:08:23+02:00"}],"dateCreated":"2018-03-27T14:57:47.00Z","dateModified":"2018-03-29T09:08:25.00Z","domain":"watersenseIT21"}]

**Comment by cdupont** [comment]
Should be fixed: https://github.com/Waziup/api-server/commit/86b3e4ad28b31aaba671ff7353366330ecc2498b
@malishahi could you check if OK and close the issue?

**Comment by cdupont** [comment]
@malishahi should I close?
