### ISSUE TITLE
Error when Executing docker-compose pull

### ISSUE THREAD

**Issue by sdabolawal** [Waziup/Platform#185]
After cloning and navigating to the platform folder, i invoke this command docker-compose pull. but i kept seeing this error message: ERROR: In file './docker-compose.yml' service 'version' doesn't have any configuration options. All top level keys in your docker-compose.yml must map to a dictionary of configuration options.
please i need help. thank you in adavnce.

**Comment by cdupont** [comment]
Hello,
you need to upgrade docker-compose to latest version. This page might help: https://docs.docker.com/compose/install/#install-compose
