### ISSUE TITLE
Server does not allow request for unadvertised object

### ISSUE THREAD

**Issue by mtuchi** [Waziup/Platform#202]
**Describe the bug**
When cloning the platform recursively, it fails when fetching submodules with the following logs 
```
error: Server does not allow request for unadvertised object 915e3db1b1aca6d01140c11a60703daecf5a68b2
Fetched in submodule path 'api-server', but it did not contain 915e3db1b1aca6d01140c11a60703daecf5a68b2. Direct fetching of that commit failed.
```

**To Reproduce**
1. `git clone --recursive git@github.com:Waziup/Platform.git`
2. See error `error: Server does not allow request for unadvertised object ....`

**Comment by cdupont** [comment]
fixed.
