### ISSUE TITLE
Create example application

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#22]
The idea is to create an end-to-end application, from gateway to display.

**Comment by cdupont** [comment]
#25
Visualization tool can be used

**Comment by CongducPham** [comment]
There are 3 temp sensors:

curl http://www.waziup.io:30026/v2/entities/Sensor3/attrs/temp/value -X GET

curl http://www.waziup.io:30026/v2/entities/Sensor6/attrs/temp/value -X GET

curl http://www.waziup.io:30026/v2/entities/Sensor10/attrs/temp/value -X GET

3 and 10 get updated every 10 mins, 6 is every 1 hour.

You have the same information on https://thingspeak.com/channels/66583

**Comment by cdupont** [comment]
Front-end is running at
http://freeboard.waziup.io/index.html#source=https://raw.githubusercontent.com/Waziup/Platform/master/UIManager/freeboard/waziup_dashboard_2.json#/
Closing this issue.
