### ISSUE TITLE
Install BD/Visualisation tools in the platform

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#25]
suggested tools:
- Kibana
- Elastic search

**Comment by cdupont** [comment]
@CharlotteEGM any progress?

**Comment by cdupont** [comment]
Instances launched at:
http://kibana.waziup.io
http://elasticsearch.waziup.io

**Comment by cdupont** [comment]
FreeBoard can also be used: https://github.com/telefonicaid/fiware-connectors/tree/develop/FreeBoard-Orion-Plugin

**Comment by cdupont** [comment]
@CharlotteEGM did you succeed?

**Comment by CharlotteEGM** [comment]
@cdupont : need to know service path used to install freeboard. It is possible that Congduc didn't use it as it is optional to push the data. We are investigating this with Sabrine

**Comment by cdupont** [comment]
Closing in favor of #51
