### ISSUE TITLE
Kubernetes identification

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#26]
Currently kubernetes doesn't have identification. To be fixed.

**Comment by cdupont** [comment]
Related: 
http://kubernetes.io/docs/admin/authorization/
https://github.com/kubernetes/dashboard/issues/1014
https://github.com/kubernetes/dashboard/issues/574

We need to set roles in kubernetes. 
- admin role: all accesses
- dev role: write access only to `waziup-test` namespace, read access to the rest

**Comment by malishahi** [comment]
Not knowing how Dashboard has been prepared, this issue #https://github.com/kubernetes/dashboard/issues/1116 might be relevant. The other related topics:

#https://github.com/kubernetes/dashboard/issues/964
#http://kubernetes.io/docs/admin/authentication/

**Comment by malishahi** [comment]
We need to understand what type of authentication are in place for this Waziup installation?

**Comment by malishahi** [comment]
It seems we are looking for creation of normal users. This is something missing in Waziup. See below.

All Kubernetes clusters have two categories of users: service accounts managed by Kubernetes, and normal users.

Normal users are assumed to be managed by an outside, independent service. An admin distributing private keys, a user store like Keystone or Google Accounts, even a file with a list of usernames and passwords. In this regard, Kubernetes does not have objects which represent normal user accounts. Regular users cannot be added to a cluster through an API call.

In contrast, service accounts are users managed by the Kubernetes API. They are bound to specific namespaces, and created automatically by the API server or manually through API calls. Service accounts are tied to a set of credentials stored as Secrets, which are mounted into pods allowing in cluster processes to talk to the Kubernetes API.

**Comment by malishahi** [comment]
Keystone Password

Keystone authentication is enabled by passing the --experimental-keystone-url=<AuthURL> option to the API server during startup. The plugin is implemented in plugin/pkg/auth/authenticator/password/keystone/keystone.go and currently uses basic auth to verify used by username and password.
For details on how to use keystone to manage projects and users, refer to the Keystone documentation. Please note that this plugin is still experimental, under active development, and likely to change in subsequent releases.
Please refer to the discussion, blueprint and proposed changes for more details.

**Comment by malishahi** [comment]
Static Password File

Basic authentication is enabled by passing the --basic-auth-file=SOMEFILE option to API server. Currently, the basic auth credentials last indefinitely, and the password cannot be changed without restarting API server. Note that basic authentication is currently supported for convenience while we finish making the more secure modes described above easier to use.
The basic auth file format is implemented in plugin/pkg/auth/authenticator/password/passwordfile/... and is a csv file with 3 columns: password, user name, user id.
password,user,uid
When using basic authentication from an http client, the API server expects an Authorization header with a value of Basic BASE64ENCODED(USER:PASSWORD).

**Comment by cdupont** [comment]
@malishahi so we need to restart kubernetes with keystone?
Did you try keystone? Can it also handle resource-based authorization? Can we use it to authorize access to our Waziup API? Is there a graphical interface to create the user name/password?

**Comment by cdupont** [comment]
postponed to V0.3

**Comment by cdupont** [comment]
@malishahi should I close this issue?

**Comment by cdupont** [comment]
Actually we still need an "admin" role in the Waziup realm able to connect to kubernetes dashboard.

**Comment by malishahi** [comment]
We need to create an admink8s role that specify users who can access k8s dashboard. Is that something you ask?

**Comment by cdupont** [comment]
yes

**Comment by malishahi** [comment]
Done. currenly under cloudplatform.waziup.io
