### ISSUE TITLE
Configure FreeBoard

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#33]
FreeBoard is installed here:
http://freeboard.waziup.io/
I need to be configured to connect to Orion context broker available at:
http://broker.waziup.io
or
http://217.77.95.64:30026

FreeBoard is installed with this Orion plugin:
https://github.com/telefonicaid/fiware-connectors/tree/master/FreeBoard-Orion-Plugin

**Comment by cdupont** [comment]
I tried without success, see attached picture.
![screenshot from 2016-11-07 11 12 14](https://cloud.githubusercontent.com/assets/484033/20054049/793ad2ac-a4db-11e6-8f0f-9e89edcb60c0.png)

**Comment by sabrine2020** [comment]
Is the broker working? I have problemes accessing the broker.
The Fiware-Service and the Fiware-ServicePath are headers used while pushing the sensors infos

**Comment by cdupont** [comment]
@sabrine2020 I have stability issues with the platform at the moment that are hard to understand for me. Anyway it seems to be back.
Do you have a link how to write those headers?

**Comment by sabrine2020** [comment]
if congduc is not using thoses headers when he pushes the sensors info, we can't add them here
could do you try with empty values?

**Comment by cdupont** [comment]
I tried with empty values as well without success.

**Comment by cdupont** [comment]
This configuration is working:
![screenshot from 2016-11-08 11 59 15](https://cloud.githubusercontent.com/assets/484033/20096585/d90f25b4-a5aa-11e6-8d9b-42a5c28a5451.png)
![screenshot from 2016-11-08 11 59 02](https://cloud.githubusercontent.com/assets/484033/20096586/d91263f0-a5aa-11e6-9441-d3f12de4cb84.png)

The data sources need to have a proper header as explained in https://github.com/Waziup/Platform/tree/master/broker

**Comment by CharlotteEGM** [comment]
First version of freeboard with UPPA sensors
http://freeboard.waziup.io/index.html#source=https://raw.githubusercontent.com/Waziup/Platform/master/UIManager/freeboard/waziup_dashboard.json#/

**Comment by cdupont** [comment]
Great! Since it is related to the example app, maybe we can move the file to a relevant folder?

**Comment by CharlotteEGM** [comment]
@cdupont Sure, I just didn't know where to put it...please put the file where you think it's best

**Comment by cdupont** [comment]
OK, thanks. Closing this issue.
