### ISSUE TITLE
FreeBoard save feature

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#36]
Currently the 'save' button in FreeBoard doesn't do anything.
http://freeboard.waziup.io/

**Comment by CharlotteEGM** [comment]
@cdupont which one ? the one when you add a datasource or the "save freeboard" general button ? 
The first one is working, i created a test datasource. For the second one, it is a feature i don't know as I don't have the same options with freeboard "outside the platform" : it must correspond to import/export buttons

**Comment by cdupont** [comment]
@CharlotteEGM it's the general button. When you click it does nothing.
Possibly it's because there is no storage configured for FreeBoard?

**Comment by cdupont** [comment]
Due to this issue https://github.com/Freeboard/freeboard/issues/127
You need to use Chrome to save FreeBoards :(

**Comment by CharlotteEGM** [comment]
Is it because it is hosted on the platform ? 
From outside the platform you can create a dashboard and it works well (no need to save anything). 
Maybe we can leave freeboard outside ? https://freeboard.io/board/YDye-w

**Comment by CharlotteEGM** [comment]
I tried to save the freeboard dashboard hosted on WAZIUP, i have now a json file of the dashboard. What should I do with it ?

**Comment by cdupont** [comment]
Some answers here: https://github.com/Freeboard/freeboard/issues/148

**Comment by cdupont** [comment]
closing as obsolete: we moved to Kibana instead of Freeboard.
