### ISSUE TITLE
Spec: visualisation requirements from MVP

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#45]

**Comment by CharlotteEGM** [comment]
I don't understand this issue... should I write down a document with visualisation requirements ?

**Comment by cdupont** [comment]
in https://github.com/Waziup/Platform/blob/master/visualisation/visualisation_spec.md

**Comment by cdupont** [comment]
@CharlotteEGM what is the status?

**Comment by cdupont** [comment]
I would close this issue since there is no change since a long time. Feel free to reopen it if needed.
