### ISSUE TITLE
Configure Elastic Search/Kibana

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#51]

**Comment by CharlotteEGM** [comment]
To push data to elastic/Kibana, we can use another tool (logstash, kafka...) or we can directly configure orion to add a new sink to elasticsearch. 
See here how to add a new sink : http://fiware-cygnus.readthedocs.io/en/latest/cygnus-ngsi/user_and_programmer_guide/adding_new_sink/index.html 

As Cygnus is based on Flume, we can use the Flume/ElasticSearch sink : https://flume.apache.org/releases/content/1.3.0/apidocs/org/apache/flume/sink/elasticsearch/ElasticSearchSink.html 

Some more infos here : https://medium.com/@omallassi/elasticsearch-kibana-flume-a1e20649b2ae#.oe74gkg6d

**Comment by cdupont** [comment]
depends on #52

**Comment by CharlotteEGM** [comment]
Elasticsearch/kibana can be now operational with an http "pull" request. Needs also logstash (ELK stack).

**Comment by CharlotteEGM** [comment]
As a recap of visualisation tools, we have for the moment : 
- freeboard, not embeddable 
- tableau public, embeddable, for historic data
- kibana, embeddable, for "real-time" analysis

I suggest that the developer create the dashboards and embbed them on WAZIUP platform for each user (accessible via password). 
Open data as a demo on WAZIUP website (publicly accessible)

**Comment by cdupont** [comment]
solved with http pull.
