### ISSUE TITLE
Integrate UGB testbed with Waziup platform

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#57]
The UGB sensors/gateways should send their data to the waziup platform (to the broker exactly).
Instructions are here: https://github.com/Waziup/Platform/tree/master/broker

**Comment by DiopBabacarEdu** [comment]
Step 1 : Preparation of sub-platform integration
--------------
 - Two gateways have been installed above the IT Center (UGB)
 - Preliminary tests are done (testing connectivity between gateways and end-devices)

Next step : Push data to Waziup Cloud

**Comment by cdupont** [comment]
@DiopBabacarEdu what is the status? Are you pushing the data to Waziup?

**Comment by DiopBabacarEdu** [comment]
https://github.com/Waziup/Platform/blob/master/gateway/IoTBridge/high_level_lora_gw/new_cloud_design/CloudWAZIUP.py
