### ISSUE TITLE
Cannot connect to broker mongodb 

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#60]
MongoDB is exposed here: 217.77.95.123:30817 (external port 30817 is mapped to mongo port 27017).
I can't connect:
```
$ mongo 217.77.95.123:30817/waziup
MongoDB shell version: 2.6.10
connecting to: 217.77.95.123:30817/waziup
```
Hangs indefinitely.

**Comment by cdupont** [comment]
@sabrine2020 @DiopBabacarEdu Any idea?

**Comment by diopBabacar** [comment]
@cdupont Is the server version same than the mongo shell version (2.6.10) ?

**Comment by cdupont** [comment]
I don't know, I use this script to deploy: https://github.com/Waziup/Platform/blob/master/broker/broker.yaml
It picks up the latest version of orion, mongodb and cygnus from https://hub.docker.com/r/waziup/

By the way, are you able to start orion/mongo/cygnus locally? I'm trying with docker-compose but the file doesn't seem up to date: https://github.com/Waziup/Platform/blob/master/broker/docker-compose.yml

**Comment by cdupont** [comment]
I was able to connect to the db with those commands:
```
$ kubectl exec -it broker-<id> -n waziup sh
# mongo
```
