### ISSUE TITLE
Website menu

### ISSUE THREAD

**Issue by ARBISWAS** [Waziup/Platform#63]
Under Documentation Add "Application Prototyping",  rename "Tutorial with "How to use WAZIUP",  rename Using WAZIUP with "Waziup Technology"

**Comment by cdupont** [comment]
Proposed documentation menu:
```
Tutorials
   Create a low cost gateway
   Create an App
   Upload your sensor data
   Visualize your data (was: freeboard)
   Use SMS
Real-World Application Prototyping
   Fish farming
   Weather station
   Cattle management
   ...  
How Waziup works
   Architecture
   Requirements
   Components
API
    API reference
    Using the Waziup API
CLI
   CLI reference
    Using the Waziup CLI
Installation
   Install Waziup platform
Release notes
```

**Comment by CharlotteEGM** [comment]
Looks great ! Easier to understand (actually who knows Freeboard ? Vizualize your data is much better)

**Comment by ARBISWAS** [comment]
To move the domain from test.waziup.io to www.waziup.io

**Comment by cdupont** [comment]
@ARBISWAS in this case we need to finish at least the main page text and some of the documentation...

**Comment by cdupont** [comment]
Done https://github.com/Waziup/Platform/commit/5ee6a0d8e0639b51b180fc85638e872f073a83fb
