### ISSUE TITLE
review and test tutorials

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#64]

**Comment by CharlotteEGM** [comment]
For the freeboard tutorial, I think @fizarbd  and Tiago both tested the tutorial and succeed to install visualisation dashboard.

**Comment by fizarbd** [comment]
I faced a small problem regarding data source. I selected - data source: datasources["IT21_temp"] as follows the page link. However it should be - datasources["IT21_temp"].TC. and after the changes it is working. I hope, it is solved now.

**Comment by CharlotteEGM** [comment]
@fizarbd , in fact you should not write it down. You should click on "datasource", and it should suggest automatically IT21_temp (you click on it), and then TC (you click on it). 

I will see how I can make this section more clear.

**Comment by cdupont** [comment]
Did you finish? Can I close?
