### ISSUE TITLE
Spec: Local Cloud

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#70]
I open this issue to discuss the spec of the "local Cloud" feature. The idea is that the gateway should be relatively autonomous with respect to the Cloud, delivering local service when Internet is not available.
- What features should the gateway have to support the local Cloud?
- What happens when an app is pushed on the Cloud platform?
- What happens when Internet is disconnected?
- How the data is accumulated/transmitted in Gateway? Should we have a broker in the gateway as well?

**Comment by ARBISWAS** [comment]
Yes,  this is a good point to start, we should start  to understand software framework interoperability between Gateway and Cloud, how local cloud and remote cloud synchronized, migration of container, etc.

**Comment by cdupont** [comment]
Too old, closing
