### ISSUE TITLE
Create an App tutorial: Register with the platform

### ISSUE THREAD

**Issue by fizarbd** [Waziup/Platform#75]
I used my name and email address for registration by using the command: deis register http://deis.waziup.io

 When I use the following command for adding ssh public key
                                              $ sudo deis keys:add ~/.ssh/id_deis.pub 
the error shows: 
                     Error: Client configuration file not found at: /home/fizar/.deis/client.json
                     Are you logged in? Use 'deis login' or 'deis register' to get started.
I don't know how to login deis.

By using the command $ deis login
Error shows - Usage: deis auth:login <controller> [options]

**Comment by cdupont** [comment]
Thanks, I did the corrections.
Closing.
