### ISSUE TITLE
Spec: access control in Orion

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#78]
How a sensor owner can restrict which users/apps can access his sensors data?
How to implement this mechanism?
I see two solutions:
- insert a "user access" field in the body of each entity. This field contains the list of authorized users.
A security proxy on top of Orion is in charge of verifying the credential of the requesting user. See http://stackoverflow.com/questions/31829814/assign-orion-entities-to-users
- user Fiware service/servicepath. In this case the user name is used as the service path. The security proxy checks that the accessing user is correct. This solution doesn't seem to allow a per sensor control.
See http://stackoverflow.com/questions/35487847/fiware-orion-access-control-on-a-per-subscription-basis

**Comment by malishahi** [comment]
This feature has to be postponed to the next milestone.

**Comment by cdupont** [comment]
Document started here: https://github.com/Waziup/Platform/blob/master/identity/access_control_spec.md
We added one sensor owner value in the entities #113
