### ISSUE TITLE
history_test.md issues

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#80]
I have some questions/small mistakes in https://github.com/Waziup/Platform/blob/master/broker/history/history_test.md:

- why creating 2 entities?
- "Start the broker history API:" section is not needed anymore
- subscription between Orion and STH: type should be SensingDevice (instead of Room), id should be Sensor1.
- header should be `--header 'Fiware-Service: waziup' --header 'Fiware-ServicePath: /TEST' in all document.

**Comment by DiopBabacarEdu** [comment]
Thanks for signaling. I have just corrected the last commit. 
One entity of type Room is created, which historical data is read.
The same example is valid for an entity of type SensingDevice.

**Comment by cdupont** [comment]
thanks, closing.
