### ISSUE TITLE
STH Comet: how to connect?

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#81]
From https://fiware-sth-comet.readthedocs.io/en/latest/data-storage/index.html
there are 2 ways of connecting STH Comet:
- formal
- minimalistic

Which one should we choose?
I understand that formal works like that:
```
Orion -> Cygnus -> MongoDB (raw data)
           |-----> STH Comet -> MongoDB (additional data)
```
Cygnus is subscribed to Orion for entity updates. It has 2 sinks, one for MongoDB, one for STH Comet.
The first sink stores the raw data. The second is STH comet, which does some additional work and also store the result in MongoDB. This additional work is some aggregating of the data (for example summing). The result is stored for caching and later retrieval.

While minimalistic is simpler:
```
Orion -> STH Comet -> MongoDB (all data)
```
In any case STH Comet is used for retrieval of data and reads from Mongo. https://fiware-sth-comet.readthedocs.io/en/latest/aggregated-data-retrieval/index.html

So, which solution should be choose?

**Comment by DiopBabacarEdu** [comment]
@cdupont I think these features provided by the formal method fit well with what we do.
@sabrine2020 what do you think?

**Comment by cdupont** [comment]
I think Cygnus is good if we have several sinks.
If we have only one, it seems we can skip it altogether and go directly to Comet.

**Comment by cdupont** [comment]
let's close in favor of using Cygnus.
