### ISSUE TITLE
Error: email is already used

### ISSUE THREAD

**Issue by cdupont** [Waziup/Platform#90]
From @Zeisberg: I was trying to register on the platform (keyclock) but did get error message but when I was trying to register again it is saying, that my email is already used. Just to let you know this strange behaviour.

**Comment by malishahi** [comment]
We need to play with the configuration. Probably since he is registered his username with his email address, could be the problem. I have activated to support email as username.

**Comment by cdupont** [comment]
Did you tested that the emails are sent? Probably we need to configure a
SMTP mail server.
Maybe the mail server from fbk can do http://sit.fbk.eu/mail/help2

**Comment by cdupont** [comment]
closing this as it seems to be solved.
