### ISSUE TITLE
Enable listing of all available / accessible sensor data 

### ISSUE THREAD

**Issue by Zeisberg** [Waziup/Platform#94]
Enable CONVENIENT and EASY listing and picking of sensor data (accessible for certain user or user group according to data rights) for creation of data vizualisation means. Make sure it becomes really easy and it does not require any pre-knowledge of id, type, servicepath, ...

**Comment by Zeisberg** [comment]
"sensor data" can be also public data from external sources, such as weather forecast/history, any public statistical data, ...etc ...which should be available in the future in waziup as well.

**Comment by cdupont** [comment]
Agreed. it should be implemented on the front-end: #89

**Comment by cdupont** [comment]
Done 295a423714b9e3fcc9e60d786f4c6defdd6e4a2d
