### ISSUE TITLE
Update TUTORIAL FOR FREEBOARD VISUALISATION

### ISSUE THREAD

**Issue by Zeisberg** [Waziup/Platform#95]
This tutorial contains wrong informatino about service and servicepath and should also get some more detailed examples to become more useful for potential implementers, this may save hours of time and keep motivation for use of the platform.

**Comment by cdupont** [comment]
Hi Sven,
what is the wrong information?
Anyway the reference for servicePath is here: https://github.com/Waziup/Platform/blob/master/broker/README.md

**Comment by Zeisberg** [comment]
Dear Corentin,

I thought the Fiware-Servicepath must be "/waziupservicepath" as we are 
using it right now for testing. Realizing now after reading 
https://github.com/Waziup/Platform/blob/master/broker/README.md, that it 
should be "/<company name>", means that the tutorial is already right 
and that I can close the issue.

Thank you for your feedback.

BR Sven

Prof. Dr.-Ing. S. Zeisberg
sven.zeisberg@innotec21.de
mobile: +49 (0)172 3061498

Am 10.01.2017 um 19:32 schrieb Corentin Dupont:

**Comment by Zeisberg** [comment]
This issue can be closed.
